export const UK_FIRE_SERVICES = [
  "Avon Fire & Rescue Service",
  "Bedfordshire Fire and Rescue Service",
  "Buckinghamshire Fire & Rescue Service",
  "Cambridgeshire Fire and Rescue Service",
  "Cheshire Fire and Rescue Service",
  "City of London Airport Fire Service",
  "Cleveland Fire Brigade",
  "Cornwall Fire and Rescue Service",
  "Cumbria Fire and Rescue Service",
  "Derbyshire Fire & Rescue Service",
  "Devon and Somerset Fire and Rescue Service",
  "Dorset & Wiltshire Fire and Rescue Service",
  "Durham and Darlington Fire and Rescue Service",
  "East Sussex Fire & Rescue Service",
  "Essex County Fire and Rescue Service",
  "Gloucestershire Fire and Rescue Service",
  "Greater Manchester Fire and Rescue Service",
  "Guernsey Fire & Rescue Service",
  "Hampshire & Isle of Wight Fire and Rescue Service",
  "Hereford & Worcester Fire and Rescue Service",
  "Hertfordshire Fire and Rescue Service",
  "Humberside Fire and Rescue Service",
  "Isle of Man Fire and Rescue Service",
  "Jersey Fire and Rescue Service",
  "Kent Fire and Rescue Service",
  "Lancashire Fire and Rescue Service",
  "Leicestershire Fire and Rescue Service",
  "Lincolnshire Fire and Rescue",
  "London Fire Brigade",
  "Merseyside Fire & Rescue Service",
  "Mid and West Wales Fire and Rescue Service",
  "Norfolk Fire & Rescue Service",
  "North Wales Fire and Rescue Service",
  "North Yorkshire Fire & Rescue Service",
  "Northamptonshire Fire and Rescue Service",
  "Northumberland Fire and Rescue Service",
  "Northern Ireland Fire & Rescue Service",
  "Nottinghamshire Fire and Rescue Service",
  "Oxfordshire Fire and Rescue Service",
  "Royal Berkshire Fire and Rescue Service",
  "Scottish Fire and Rescue Service",
  "Shropshire Fire and Rescue Service",
  "South Wales Fire and Rescue Service",
  "South Yorkshire Fire & Rescue",
  "Staffordshire Fire and Rescue Service",
  "Suffolk Fire and Rescue Service",
  "Surrey Fire and Rescue Service",
  "Tyne and Wear Fire and Rescue Service",
  "Warwickshire Fire and Rescue Service",
  "West Midlands Fire Service",
  "West Sussex Fire & Rescue Service",
  "West Yorkshire Fire and Rescue Service",
] as const;
